sudo: false
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: fVwFBG9xhN8+pSInaMnp8KS72bTXYTvrK850/H31yTeF4ixTWLZkjQUe1+URPKl5DYV9kC5hYZZMjDYWSrTnGVOJFdV6Fxxxw7M9KWnr3Zqj662Uj83S6ZfoFFqmXde2lY9s5wZ11vUfBPyiQMXF3DQ92Xaxo3WwGGQ0a6YxinZ3Jo/1oy92YMK1LsoRYw97ZujrLsDgQSGJtmziMfalLb8cb1xtd0SKvk2zit2zVJTbmzE9VjJbmEyWIx52ks4lUIZ2M1wFyFHyiNlrLvrl0regpj/c1k1//5bdtUbMD4UGWMS2LfU/ieVz9aJZ6YJIOvFohBLTG6g36pd5ec3dtWVgWzTOgcJd8MYEN+1nDhvEL+rQH/4ZtBePFd50S6x4lSQNenEUQE4ZBQSwywTHptUC4rhTO9cK3TrWDJfdzwQbgJe3xgfhiVW2VyFp6a0vigBYTHnGrPc4iiKsQ1SEUz38o7S4S0l34h2/FHDfy4xauI3lFMRwKWuXu+Gni1yMRfiPoo62tZE/FAyqg9/d39BA/+6RxKr1LytEiDTlwyrMdKvo58rF8hIeZX/FvL2etXnAF36o2s5eUC4/de72CSEP3YtegmDC/QPYJ2K8rvtWVn5pEMi2JFJZXSjxoDCkpZ/YqPa6uBePA988f8tRDSNd2eSB+MkdVxfkDutCTBY=
  - secure: kg2RROJmAAG+ScloAIjnxU4uzY8WsdIWEa6v+uxot6chaWA4G63Aye4oddRs+rtu0iDBtqPEPFaIGptmE9KyOEOjgp3BDLsiLZEc5RXkuGcyq4xUPFstZtJA7OlT+HsMBj02yOyyC/HDh/egGQ3Ar1Ay6g+fcFP9in8bKIqUIpfKXrLUnQGkZ4E6ij6G/nx/SJbQqtPLf0B4gUiOtNg7FM0LgSLS/wLl8MszQ+S5tEr4pC1nezmQt/8hrlNWEng6jdEfbJOZ9pczGIFNjzbO3elYw1Jl5EFIwGwZyTBzP+utINDGXkAkaIXtnuXTyaJFGyrOllq0V1/ohQFSYTU1sZZdoAuM29a3MgTzH1LA9ecTrma94xDNCi2tzKxc41khFyA1NogPtodX0r6xDiy7EFvQyBwfqzeBiZiUGa41ObXBhl+BVvnABy5ORXrjTT8keZoWgeWFJbUHXmS53aIEuarSdb/pNKscmLXhYdM4YMcZputawdles4iM49Jhs2vonuR7Nd+Y6pI76TNhkBtonX+4ylgWlnUxeZ4KqE5q3+ZUV1ajLKX7AZ4tZ5a96hmgJDJxh3hPG9j00m0tFSOVlgQFBV4/MD6i1zRApv7GqOm9JUbkbPZlklkwmhP+GY+mIU9DF5BOlXxg7PsLQDCYYubBsMXDCNd1Jem5r7H4bc0=
